version: "3.8"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    environment:
      NODE_ENV: development

  api-server:
    build:
      context: ./api-server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./api-server:/usr/src/app
    environment:
      NODE_ENV: development

  websocket-server:
    build:
      context: ./websocket-server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./websocket-server:/usr/src/app
    environment:
      NODE_ENV: development
